full_name = "Gloria Anne"
description = "I am an office coordinator in Mazraa making sure that the wheel keeps turning and the lights stay on!"
why_threefold = ""
function = ""
rank = 0
project_ids = []
contribution_ids = []
nationality = " "
